# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Arduino-Remote' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Arduino-Remote
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'SwiftSocket'

  target 'Arduino-RemoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Arduino-RemoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
